version: '3'
services:
  # Build container for java and gives port 8080. Adds network for app and db
  app:
    build: .



  # Builds container for db server, sets root password and gives port 3306 for container.
  db:
    build: db/.
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - "33060:3306"