version: '3'
services:
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - scad-db-network

  db:
    build: db/.
    command: --default-authentication-plugin=mysql_native_password --bind-address=0.0.0.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
    ports:
      - "3306:3306"
    networks:
      - scad-db-network
    expose:
      - "3306"
    volumes:
      - mysql-data:/var/lib/mysql

networks:
  scad-db-network:
    driver: bridge

volumes:
  mysql-data:
