name: Java and MySQL Workflow
on: push

jobs:
  build:
    name: Build and Run Java Application
    runs-on: ubuntu-20.04
    services:
      db:
        image: mysql:latest
        env:
          MYSQL_ROOT_PASSWORD: example
        ports:
          - "3306:3306"
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
      app:
        image: SCAD-0.1.0.2-jar-with-dependencies
        ports:
          - "8080:8080"
        depends-on:
          - db
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Build with Maven
        run: mvn package

      - name: Build Docker image
        run: docker build -t SCAD-0.1.0.2-jar-with-dependencies .

      - name: Run Docker image
        run: docker run --network se-methods --name semcontainer SCAD-0.1.0.2-jar-with-dependencies

      - name: View logs
        run: docker logs semcontainer
