name: Java and MySQL Workflow
on: push

jobs:
  build:
    name: Build and Run Java Application
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Build with Maven
        run: mvn package

      - name: app
        run: mvn -Dtest=com.napier.sem.mytest test

      - name: Package and Run docker compose
        run: |
          mvn package -DskipTests
          docker-compose up --abort-on-container-exit

      - name: View logs
        run: docker logs semcontainer
